
AutoCompressor:
  material: "OBSIDIAN"
  name: "<blue>Auto Compressor</blue>"
  lore:
    - "hey"
    - "bye"

SuperAutoCompressor:
  material: "GLASS"
  name: "<red>Super Auto Compressor</red>"
  lore:
    - "it"
    - "is"
    - "a"
    - "super"
    - "auto"
    - "compressor"

AutoCompressItems:
  - item-name: "stony"
    compressed-item-name: "not stony"
  - item-name: "cooly"
    compressed-item-name: "not cooly"

SuperAutoCompressItems:
  - item-name: "bla"
    compressed-item-name: "not bla"
  - item-name: "bli"
    compressed-item-name: "not bli"